version: '2.3.3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=raveline
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=Go_DB      
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql   

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "junior@email.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - "54321:80"
    depends_on:
      - postgres